### ISSUE TITLE
Alternative code (sandbox included)

### ISSUE THREAD

**Issue by dbismut** [E-Kuerschner/useAudioPlayer#1]
Hey @E-Kuerschner thanks for the lib, the concept is great.

I've made some specific changes that should optimize it in this sandbox if you want to have a look:
https://codesandbox.io/s/audio-player-gs1lm

I've specifically worked on making it mount / unmount proof and reducing the amount of code + dependency on lodash which increases the bundle size unnecessarily. 

EDIT: happy to make a PR if you like it.

**Comment by E-Kuerschner** [comment]
@dbismut solid additions! Those are some great improvements. By all means please put up a PR, it will be easier for me to visualize the changes that way too
