### ISSUE TITLE
Export AudioPosition interface from useAudioPosition

### ISSUE THREAD

**Issue by jedhazaymeh-toast** [E-Kuerschner/useAudioPlayer#103]
**Is your feature request related to a problem? Please describe.**
Instead of having to a create a duplicate of the `AudioPosition` interface inside `react-use-audio-player/dist/useAudioPosition`, I would like to be able to import the interface from `react-use-audio-player` (similar to the `AudioPlayerControls` type).

**Describe the solution you'd like**
Export the interface `AudioPosition` from `react-use-audio-player/dist/useAudioPosition`, so it is accessible from `react-use-audio-player`.

**Comment by E-Kuerschner** [comment]
hey @jedhazaymeh-toast thanks for the request. I'll try to get to this in a couple of weeks when I have a weekend to dedicate to this. Would you like to try implementing yourself before then? I'll be happy to review the PR if you tag me

**Comment by E-Kuerschner** [comment]
@jedhazaymeh-toast these interfaces should be available in version 1.3.1. Thanks!
