### ISSUE TITLE
usePosition doesnt work anymore

### ISSUE THREAD

**Issue by geniux-dev** [E-Kuerschner/useAudioPlayer#109]
After installing alpha usePosition is not found,

**Comment by E-Kuerschner** [comment]
Hi @geniux-dev pls see the announcement post for v2. useAudioPosition is being dropped in favor of client-specific implementations. You can use the "getPosition" method within an interval to build your own version of this

**Comment by geniux-dev** [comment]
thanks will test again now

**Comment by E-Kuerschner** [comment]
@geniux-dev here is an example:
https://github.com/E-Kuerschner/useAudioPlayer/blob/v2.0/examples/src/AudioSeekBar.tsx#L26
