### ISSUE TITLE
starting with empty src loads infinitely

### ISSUE THREAD

**Issue by braco** [E-Kuerschner/useAudioPlayer#110]
One might want to initialize the player without a src to use `load()` later, but 

`useAudioPlayer({ src: null })`

seems to start with an infinite load. Is this expected behavior?

**Comment by ZimNovich** [comment]
> seems to start with an infinite load. Is this expected behavior?

Yes, it is the default behavior:
```
export const initialState: AudioPlayerState = {
    loading: true,
    playing: false,
    stopped: true,
    ended: false,
    error: null,
    duration: 0,
    ready: false
}
```
They initialize the state with `loading: true`.

**Comment by E-Kuerschner** [comment]
hey @braco the behavior you are interested in is the [default for version 2 which is currently available for testing on its alpha version.](https://github.com/E-Kuerschner/useAudioPlayer/discussions/108) Please take a look at this version and provide any feedback if you'd like!

For now, on any 1.x.x version you must have the src ready at the time the hook is initialized.
