### ISSUE TITLE
Download audio

### ISSUE THREAD

**Issue by braco** [E-Kuerschner/useAudioPlayer#111]
I'm not sure how to support downloading the audio file that was loaded.

Is there a way to do this?

**Comment by E-Kuerschner** [comment]
hey @braco, downloading the audio is outside the scope of this hook. It is only designed to give you the means to control playback within a react application. Assuming you have the URI of the audio you should be able to start downloading it with a simple fetch request on your own.

PS [version 2 of this library is available for testing on alpha](https://github.com/E-Kuerschner/useAudioPlayer/discussions/108) if you are interested in providing feedback. Thanks!
