### ISSUE TITLE
isLoading boolean

### ISSUE THREAD

**Issue by brianshano** [E-Kuerschner/useAudioPlayer#116]
**Problem**

When streaming an internet radio station
e.g. in the example `/globalAudio/state` and select "streaming internet radio", there is a slight delay while it loads the stream. There is no visual queue to show that the stream is loading. 

**Solution**

If the useGlobalAudioPlayer had a boolean for isLoading, it would be delightful!
I tried using the `isReady` boolean, but it doesn't represent stream loading as it's deemed ready before that. 

**Alternatives**

At the moment I'm setting a useState  based on the call to 'load' a station and unsetting once the `onload` method is true but that isn't easily available as a global method then. 

**Additional context**

Loving the new useGlobalAudioPlayer 🎉

**Comment by E-Kuerschner** [comment]
@brianshano thanks for reporting this! This was something I noticed as well and meant to document. If you have any ideas let me know. I don't even think the base howler library was handing this well, but I will think about what we can do

**Comment by E-Kuerschner** [comment]
hey @brianshano have you experienced this issue in any other context outside the example application? If so, I'd love to see a sandbox so i can test against other use cases as well

**Comment by E-Kuerschner** [comment]
hey @brianshano v2.1.0 adds an isLoading boolean and also addresses some issues around streaming audio. Give it a shot to see if solves your issue! Closing for now

**Comment by brianshano** [comment]
Yes! 
That works wonderfully!
It's now really simple to display when the radio stream is loading. 

Also I noticed passing the initialVolume prop works perfectly now too. 

Great work, thanks 🙌
