### ISSUE TITLE
Use howler typings for input arguments

### ISSUE THREAD

**Issue by navneetgarg123** [E-Kuerschner/useAudioPlayer#12]
**Is your feature request related to a problem? Please describe.**
Using the official typings of howler where appropriate makes it a consistent interface for all consumers.

**Describe the solution you'd like**
leverage the howler typings for the input (and possibly internal) arguments/properties. 

**Describe alternatives you've considered**
`@ts-ignore` or override the typings from the consumer code

**Comment by E-Kuerschner** [comment]
I was thinking about this... I'm not sure yet if we should keep howler as an implementation detail. Would using its types make client code too dependent on howler details? Consider, for example, if in the far future this hook is rewritten to use the web audio api directly rather than howler.
