### ISSUE TITLE
Error in the Readme, fade arg says second not ms

### ISSUE THREAD

**Issue by theslantedroom** [E-Kuerschner/useAudioPlayer#125]
**Describe the bug**
in the read me and https://www.npmjs.com/package/react-use-audio-player

duration: number (the length in seconds) 

should be

duration: number (the length in milliseconds)

**Comment by E-Kuerschner** [comment]
thanks for noticing this @theslantedroom! Do you mind putting up a PR for the fix? Happy to review/merge

**Comment by theslantedroom** [comment]
> thanks for noticing this @theslantedroom! Do you mind putting up a PR for the fix? Happy to review/merge
PR open!
