### ISSUE TITLE
Play Automatically

### ISSUE THREAD

**Issue by Tini79** [E-Kuerschner/useAudioPlayer#142]
Is it possible to make the audio play automatically? If it is, how? Here I only use load and I need to do click event to make the music played.

**Comment by E-Kuerschner** [comment]
Hi @Tini79 the `autoplay` option should do what you want!

**Comment by E-Kuerschner** [comment]
There is a section in the README about it

**Comment by TuKun33** [comment]
> Is it possible to make the audio play automatically? If it is, how? Here I only use load and I need to do click event to make the music played.

When I `pause()`  or `stop()` one audio in playing , then `load()` another audio, it doesn't work, Even load in the `setTimeot`
