### ISSUE TITLE
Upgrade to react 19

### ISSUE THREAD

**Issue by RunRanger** [E-Kuerschner/useAudioPlayer#148]
Since react 19 is officially released, the dependency can be upgraded to react 19 for better compatibility

**Comment by E-Kuerschner** [comment]
@RunRanger thanks for the heads up. I have a few other React improvements I would like to make in my upcoming time off which includes refactoring to use useSyncExternalStore (#136). Perhaps I can jump up in v19 as well in that laundry list of things
