### ISSUE TITLE
Audio playing multiple streams over itself

### ISSUE THREAD

**Issue by beamercola** [E-Kuerschner/useAudioPlayer#18]
I've built a small playlist-like setting similar to the example.

Here's my click method on a list of tracks
```js
  const handleClick = track => {
    setCurrent(track);
    load({ src: track.url, autoplay: !playing });
  };
```

Clicking around on the tracks mostly works - but then one will get "stuck" and you have to refresh to get it to stop.

I'm wrapping the entire thing in a single `AudioPlayerProvider` so not dealing with multiple contexts or anything.

I tried adding a `stop()` in there before `load()` but same problem.

**Comment by beamercola** [comment]
And thank you for this library, so far it's been really nice to use.  I hope this issue is just user error

**Comment by E-Kuerschner** [comment]
@beamercola, thanks for opening up the issue. 

If I am understanding correctly, you are loading multiple audios in succession. At some point you are not able to load the next and the current sounds remains playing regardless of what you do?

**Comment by beamercola** [comment]
Each one loads, but they start playing on top of eachother.  you can see the player [here](https://light.page/dropoutfm) - if you click between tracks rapidly you should be able to notice.

**Comment by E-Kuerschner** [comment]
Alright thanks that helps a lot! I'll try to get to this some time this week. If you're interested feel free to mess with the source code. I'm definitely open to contributors and pull requests!

**Comment by beamercola** [comment]
Thank you!  I wish I was that smart, but I'll continue poking around in there...

**Comment by beamercola** [comment]
This is likely where the issue lies I'd guess.  All seems legit

```js
            let wasPlaying = false
            if (playerRef.current) {
                // don't do anything if we're asked to reload the same source
                // @ts-ignore the _src argument actually exists
                if (playerRef.current._src === src) return
                wasPlaying = playerRef.current.playing()
                if (wasPlaying) {
                    playerRef.current.stop()
                    // remove event handlers from player that is about to be replaced
                    playerRef.current.off()
                    playerRef.current = undefined
                }
            }
```

**Comment by E-Kuerschner** [comment]
@beamercola could you paste me the relevant source code of the player you sent to me that is experience the "stuck" behavior? I want to see your exact usage of the library

**Comment by E-Kuerschner** [comment]
@beamercola i just made a new release v0.0.13 which fixed an underlying issue. Im curious if this will solve your issue. Can you please try to recreate with this new version and let me know what you find?
Thanks

**Comment by beamercola** [comment]
Like magic!  Thank you so much!

You should set up github sponsors, I'd be happy to support

**Comment by E-Kuerschner** [comment]
Awesome! Glad to help! And thanks man I appreciate it. I'll think about it. I'm not too familiar with the sponsors feature

**Comment by almightybob** [comment]
I'm having this Issue with react-native-web and useAudioPlayer v. 1.2.4
