### ISSUE TITLE
useAudioPosition to support seeking

### ISSUE THREAD

**Issue by richpjames** [E-Kuerschner/useAudioPlayer#21]
First of all this project is amazing and has saved me a lot of hassle - thank you. 

In the docs it suggests that the ```useAudioPosition``` could be used for a seek bar which would be really great. However, from what I understand, it only returns the read-only 'position' and 'duration' values so it can't actually be used for seeking.

It would be helpful if ```useAudioPosition``` returned a function that could set the current  playback position

**Comment by E-Kuerschner** [comment]
hey @richpjames thanks for opening the issue. Right now useAudioPosition returns the real-time positional information. This could be used to calculate the current position in respect to the duration which is also returned from the hook. Perhaps describing it as a seek-bar in the docs is a little misleading, but there is a `seek` method returned from the other main hook, `useAudioPlayer`

**Comment by E-Kuerschner** [comment]
If you were already aware of `seek` in the other hook, do you think it would be helpful to return it from useAudioPosition as well?

**Comment by richpjames** [comment]
Thanks for getting back to me.
As the docs suggest the hook is really useful for creating a seek bar and I there is a definite use case for returning a seek function from it.
Otherwise I would have to pass the seek function through the relevant components to be in the same place as the ```useAudioPlayer``` hook.
It's a minor detail I know but perhaps worth considering

**Comment by E-Kuerschner** [comment]
you should be able to use `useAudioPlayer` in any component within the AudioPlayerContext. This means that several components could be using it at one time so you shouldn't have to pass seek down if you use the hook in the same component that is already using, `useAudioPosition`. 

However, I can see the argument for adding seek to `useAudioPosition` as well. At the very least its convenient. I'll keep the issue open and slate that for the next patch

**Comment by richpjames** [comment]
Yes I understand that I could use it in any place within the AudioPlayerContext but is the audio currently playing shared across that context too? 
My understanding is that it is not.

**Comment by E-Kuerschner** [comment]
Yup! The lib currently supports one sounds being played at a time so that one sound (managed by the context) is shared everywhere. So you can drop a useAudioPlayer in any component inside the context and control that one audio that was loaded.

**Comment by richpjames** [comment]
Oh, excellent - thanks for clarifying

**Comment by richpjames** [comment]
Oh, excellent - thanks for clarifying

**Comment by E-Kuerschner** [comment]
@richpjames your requested feature has been merged in and is available in version 0.0.14

**Comment by richpjames** [comment]
@E-Kuerschner amazing, thank you.
