### ISSUE TITLE
Expose Howler's volume control

### ISSUE THREAD

**Issue by richpjames** [E-Kuerschner/useAudioPlayer#23]
It would be really good to be able to let the user control the volume with a range slider as opposed to a binary on/off control. 

I know Howler lets you control volume on a 0 - 1 sliding scale so it'd be really helpful if you could expose this control.

The mute/unmute option works sufficiently for now but a range option would be a massive plus.

Thanks

**Comment by E-Kuerschner** [comment]
Agreed! Let's get that into the next release

**Comment by richpjames** [comment]
excellent work!
