### ISSUE TITLE
position is sometimes Howl

### ISSUE THREAD

**Issue by richpjames** [E-Kuerschner/useAudioPlayer#28]
The position returned from useAudioPosition is occasionally the Howl object.
My understanding is that it should always be a number.

This seems to happen only when the track has yet to start or when the position is less than a second 

 - Browser/ browser version: 
Firefox, Safari, Chrome

Thanks

**Comment by E-Kuerschner** [comment]
@richpjames yeah that is a quirk of the underlying Howler library. I think we can def abstract that away for a clearer API

**Comment by humbkr** [comment]
@E-Kuerschner it's still happening in version 0.0.18 when the audio file is not loaded yet.

I think it should alway return a number (0 in this case) to match the function signature.

**Comment by E-Kuerschner** [comment]
@humbkr lemme reopen this and investigate. Thanks for commenting.

**Comment by E-Kuerschner** [comment]
Fixed in v1.0.0
