### ISSUE TITLE
Player doesn't play radio stream

### ISSUE THREAD

**Issue by AWydra** [E-Kuerschner/useAudioPlayer#34]
**Describe the bug**
Player doesn't play radio stream. Howler docs says that live stream can only be played through HTML5 Audio, but I can't trigger it.

```
sound =  new Howl({
  src: data.src,
  html5: true, // A live stream can only be played through HTML5 Audio.
  format: ['mp3', 'aac']
});
```

**To Reproduce**
1. Set src key in useAudioPlayer to play radio stream, e.g. 
https://eu6.fastcast4u.com/proxy/wydra?mp=/1

**Expected behavior**
Player plays radio stream. I recommend add optional argument `html5: true` to play in `<audio>` tag.

**Environment:**
 - Browser/ browser version: Chrome 81
 - Library version: 0.0.17
 - React version: 16.12
 - Node version: 10.15.3

**Comment by E-Kuerschner** [comment]
@AWydra just made a release that supports the html5 option. Please give it a try using version 0.0.18. Thanks!
