### ISSUE TITLE
odd error message when copy/pasting example code into gatsby app...

### ISSUE THREAD

**Issue by rchrdnsh** [E-Kuerschner/useAudioPlayer#4]
Hello,

Trying to try out the package and ran into this issue while trying to give it a spin:

<img width="1036" alt="Screen Shot 2020-01-13 at 11 55 29 PM" src="https://user-images.githubusercontent.com/7884263/72324710-635cae00-3660-11ea-887a-79c387f5ea5f.png">

don't know what it means myself, but curious if you have any thoughts what this might mean.

**Comment by E-Kuerschner** [comment]
hey @rchrdnsh thanks for opening the issue! Let's figure this out!

I'm not sure myself, looking at the compiled code i don't see anything out of the ordinary. Do you have steps to reproduce this error condition?

What versions of the library and or Gatsby are you using?

Thanks.

**Comment by rchrdnsh** [comment]
oi!

Never mind, I didn't thoroughly read and understand the directions very well...apologies, I was trying to try this out late at night after being sick all day 🤢

All good now! 😁 (The package and also me 🙃 )
