### ISSUE TITLE
Audio does not seem to be playing on the iPhone speaker...

### ISSUE THREAD

**Issue by rchrdnsh** [E-Kuerschner/useAudioPlayer#5]
ok, here's an actual issue, I think. I set up your package on a page in an app I'm building to test it out:

https://rykr.netlify.com/test/

...and it seems to work fine everywhere I have tested it except for my iPhone, in which I hit the play button after the audio has loaded, but no sound plays through the phone speaker. If I connect it to another speaker through a cable or bluetooth it seems to work, just not the phone speaker itself.

Kind of an odd issue, I know, but wondering if you have ever heard of this kind of thing at all. I am aware that the web audio API has historically had a few issue in safari and webkit, but I don't know why it's not working through the speaker only...quite odd...

This is how I set up your package on that page in the app, just basically copying the example:

```jsx
import React from 'react'
import styled from 'styled-components'
import { useAudioPlayer } from 'react-use-audio-player'
import { AudioPlayerProvider } from 'react-use-audio-player'

import baktun from '../content/music/baktun/baktun.mp3'

const Box = styled.div`
  grid-column: 1 / 8;
  align-self: center;
  justify-self: center;
  border: 1px solid white;
  width: 16rem;
  height: 20rem;
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  border-radius: 32px;
`

const Button = styled.button`
  margin: 1rem;
  padding: 0.75rem 2rem;
  background: #006964;
  border: 1px solid #00fff3;
  border-radius: 16px;
  color: white;
  font-size: 32px;
`

const Name = styled.h1`
  margin: 1rem;
  padding: 0;
  font-family: 'Odachi', sans-serif;
  font-size: 32px;
`  

const AudioPlayer = ({ file }) => {
  const { play, pause, ready, loading, playing } = useAudioPlayer({
    src: file,
    format: "mp3",
    autoplay: false
  })

  const togglePlay = () => {
    if (playing) {
      pause()
    } else {
      play()
    }
  }

  if (!ready && !loading) return <div>No audio to play</div>
  if (loading) return <div>Loading audio</div>

  return (
    <div>
      <Button onClick={togglePlay}>{playing ? "Pause" : "Play"}</Button>
    </div>
  )
}

const Test = () => {
  return (
    <AudioPlayerProvider>
      <Box>
        <Name>b'ak'tun</Name>
        <AudioPlayer file={baktun} />
      </Box>
    </AudioPlayerProvider>
  )
}

export default Test
```

**Comment by E-Kuerschner** [comment]
@rchrdnsh hmmm that is very odd indeed. I don't see how connecting a speaker would change anything from the web's perspective. I visited the link you shared using Chrome on my Google Pixel and I was able to play audio (and hear it) just fine. Could this be an issue with your phone?

Your code looks fine btw! Nothing stands out there.

**Comment by rchrdnsh** [comment]
hmmm...ok, I'll try to test it out on more devices and see if the problem persists any predictable way and let you know what i find :-)

**Comment by rchrdnsh** [comment]
I have been able to test on a few phones so far, and have found that it played back fine on a Samsung Galaxy S10 and an iPhone 11, but not on two different iPhone 11 Pros (one was a Pro Max), so I will keep testing on more phones as I get my hands on them.

**Comment by E-Kuerschner** [comment]
i think what is most important to track is the browsers you are using and their versions not necessarily the phone model. What you are experiencing may just be browser compatibility issues with Web Audio/HTML5 audio. 

I'm going to close this for now as there is no reliable way to reproduce.
