### ISSUE TITLE
Cannot read property 'player' of null

### ISSUE THREAD

**Issue by carmandale** [E-Kuerschner/useAudioPlayer#71]
If you have an HTML element inside a react three fiber drei Html component, it won't "wait" for the audio player component to regiter or mount and I get this error.

Cannot read property 'player' of null

**Comment by carmandale** [comment]
Even if I do...

`const value = useAudioPlayer()
  const { ready } = value
  console.log(value)
  if (ready) {
    return (
      <div className="player">
        <3D react scene with HTML element />
      </div>
    )
  }`

**Comment by Vang-z** [comment]
I have meet the same question. Are you find some way to fix that?

**Comment by E-Kuerschner** [comment]
hi @carmandale thank you for opening this. Can you describe more about your issue? What library are you using this with? Perhaps we will need to collaborate on a fix if I am not familiar

**Comment by logandeancall** [comment]
@E-Kuerschner I am experiencing the same issue while attempting to load the example hook code in the README w/in storybook.

**Comment by chwzr** [comment]
same here with nextjs. looks like its ssr related?

**Comment by argkont** [comment]
I have the same problem on GatsbyJS and the solution was wrap the component inside the AudioPlayerProvider, hope this usefull 👍

**Comment by RunRanger** [comment]
The Provider has to be named in an upper component. The hook is called bevor the provider is returned, that's why the context (=player) is null.
Make a wrapper-component or use a component above.

**Comment by JanVeb** [comment]
> The Provider has to be named in an upper component. The hook is called bevor the provider is returned, that's why the context (=player) is null.
> 
> Make a wrapper-component or use a component above. You can look at the example on this git repository. The author is using two different components. You don't need to provide a value for the Provider.

You could really give an example...

**Comment by JanVeb** [comment]
Tried this it doesn't work, this was only use I could find in examples

    <AudioPlayerProvider>
      <div>
        <button onClick={togglePlayPause}>{playing ? 'Pause' : 'Play'}</button>
      </div>
    </AudioPlayerProvider>

**Comment by JanVeb** [comment]
Solved it by wrapping AudioPlayer in   AudioPlayerProvider in imported file
    <AudioPlayerProvider>
        <AudioPlayer />
      </AudioPlayerProvider>

**Comment by codewithfeeling** [comment]
@JanVeb's solution worked for me - make sure the `AudioPlayer` is wrapped inside `AudioPlayerProvider` (doesn't matter how far up your component tree this is - I've wrapped it at app level) - thanks :)

**Comment by E-Kuerschner** [comment]
yep! the solution @JanVeb provided is the way the hook is designed to function. I can try and update the docs to make this more clear
