### ISSUE TITLE
How to automatically play when switching audio

### ISSUE THREAD

**Issue by Vang-z** [E-Kuerschner/useAudioPlayer#73]
I try to use the `onend` call back function to change the audio src, but it didn't automatically play, even I use the `player.paly()` to play the audio, but it's no use. So could you give me a solution to solve this problem.

**Comment by E-Kuerschner** [comment]
hi @Vang-z thank you for opening this. Can you please provide the following?

- library version
- browser/platform
- a snippet of the code you are trying

I will need to reliably reproduce your issue before I can start debugging this. Hopefully I will be able to address over the weekend.

**Comment by Vang-z** [comment]
library version: `1.2.4`
browser/platform: `chrome 96.0.4664.110`
a snippet of the code:
```typescript
// Initial Code
const PlayerCore: React.FC<{ song: any }> = ({song}) => {
  const classes = playerCoreStyles();

  const dispatch = useDispatch();
  const player = useSelector(state => state.musicPlayer);

  const {togglePlayPause, play, pause, volume, playing} = useAudioPlayer({
    src: song.src,
    autoplay: player.autoplay,
    volume: player.volume / 100,
    html5: true,
    "onend": () => {
      dispatch(musicPlayerSlice.actions.dispatchAutoplay(true));
      dispatch(musicPlayerSlice.actions.dispatchEnd(true));
    }
  });
  // render code
}
```

```typescript
// because of the useAudioPlayer function don't accept the audio scr array
// I have a bad solution, It will to change the src of the useAudioPlayer, when the player was ending.
  useEffect(() => {
    if (player.autoplay && player.end) {
      dispatch(musicPlayerSlice.actions.dispatchSrc(newSrc);
      dispatch(musicPlayerSlice.actions.dispatchEnd(false));
    }
  }, [dispatch, togglePlayPause, player, playing])
```
But there are still problems with this, if the `newSrc` equal to the old src, we must use `play()` function to play the audio. By the way `useAudioPlayer` is a excellent lib for react :)

**Comment by E-Kuerschner** [comment]
@Vang-z i can see one issue with your useEffect. If I'm understanding what you want to do correctly, you want to begin the necxt sound when the previous one ends. However, based on your second code snippet I don't think that is what is happening. If you want to trigger some behavior at the end of a sound you can use the onend callback in the options you pass to the main            hook.

Please try putting  your "play next track" logic in there and not in this effect first. Please let me know if I misunderstood your issue.

**Comment by Vang-z** [comment]
I'm sorry that my description is not very clear. I created a example on [codesandbox.io](https://codesandbox.io/s/vigilant-sun-nuldy?file=/src/example.tsx). Thx for your work!

**Comment by E-Kuerschner** [comment]
Thanks for setting that sandbox up. I will investigate deeper tomorrow. In the meantime perhaps try using the `load` method from useAudioPlayer. That may be the only way to support loading subsequent sounds for now.

**Comment by Vang-z** [comment]
Okay, thx a lot!

**Comment by E-Kuerschner** [comment]
@Vang-z - good news! I was able to achieve autoplaying the next song without putting up a new release. Please review the code below and let me know if it doesn't work for you. Would you mind also advising how the documentation can be improved such that someone such as yourself could implement something like this on their own? Also feel free to push up a PR yourself if you would like to contribute to the docs

```
const songs = [sound1, sound2];
export function AutoPlayNextSound() {
    const [songIndex, setSongIndex] = useState(0);

    const { togglePlayPause, ready, playing } = useAudioPlayer({
        src: songs[songIndex],
        html5: true,
        autoplay: true,
        onend: () => {
            setSongIndex(index => index + 1);
        }
    });

    const { position, duration, seek } = useAudioPosition({
        highRefreshRate: true
    });

    if (!ready) return <h1>audio {songs[songIndex]} is loading</h1>
    return (
        <>
            <div>Currently playing: {songs[songIndex]}</div>
            <button onClick={togglePlayPause}>
                {playing ? "pause" : "play"}
            </button>
            <button onClick={() => seek(duration * 0.99)}>skip to end</button>
            <div>
                {position.toFixed(2)} / {duration.toFixed(2)}
            </div>
        </>
    );
}

export default AutoPlayNextSound;
```

**Comment by Vang-z** [comment]
I'm sorry for not replying to you in time, because I was ill during this period.  I will test these methods as soon as possible and hope they work as scheduled. Thank you!
