### ISSUE TITLE
Loop audio

### ISSUE THREAD

**Issue by geniux-dev** [E-Kuerschner/useAudioPlayer#91]
When I pass **loop** prop it works but the thing is I need to update the **loop** prop while the audio is playing.

When I do that I doest update unless I re-render

**Comment by E-Kuerschner** [comment]
thanks for the bug! i've added it to the backlog. I'm hoping to spend a weekend soon to apply some fixes.

**Comment by E-Kuerschner** [comment]
Working on this for [v2](https://github.com/E-Kuerschner/useAudioPlayer/discussions/106)

**Comment by liho00** [comment]
any idea on how to achieve loop attribute in v1?

**Comment by E-Kuerschner** [comment]
@liho00 unfortunately v1 doesn't support this at this time. I am about to release an alpha for v2. Would you be willing to test it out for your use case when its ready?

**Comment by liho00** [comment]
> @liho00 unfortunately v1 doesn't support this at this time. I am about to release an alpha for v2. Would you be willing to test it out for your use case when its ready?

sure, looking forward

**Comment by E-Kuerschner** [comment]
@liho00 hi! The alpha version for v2 has been published and is ready to test!
https://github.com/E-Kuerschner/useAudioPlayer/discussions/108

**Comment by geniux-dev** [comment]
How can we upgrade to v2?

**Comment by E-Kuerschner** [comment]
> How can we upgrade to v2?

@geniux-dev check out the post here: https://github.com/E-Kuerschner/useAudioPlayer/discussions/108

**Comment by E-Kuerschner** [comment]
closing since i am planning to merge v2 soon
